### ISSUE TITLE
addCard method does not work

### ISSUE THREAD

**Issue by Sereekjan** [PayBox/SDK_Android_input#3]
When I'm trying to add the card via method PBHelper.getSdk().addCard("some_id", "some_url")

org.json.JSONException: Mismatched link and head at character 872 of 
```<!DOCTYPE html>
<html>    
          <head>        
          <title>Not found</title>        
          <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">        
          <style>            html, body {                height: 100%;            }            body {                margin: 0;                padding: 0;                width: 100%;                color: #B0BEC5;                display: table;                font-weight: 100;                font-family: 'Lato';            }            .container {                text-align: center;                display: table-cell;                vertical-align: middle;            }            .content {                text-align: center;                display: inline-block;            }            .title {                font-size: 72px;                margin-bottom: 40px;            } </style>    
          </head>    
          <body>        
          <div class="container">            
          <div class="content">                
          <div class="title">Страница или метод не найдены.</div>                
          <div>                    
          <h1></h1>                
          </div>           
          </div>        
          </div>    
          </body>
</html>

at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
    at org.json.XML.parse(XML.java:313)
    at org.json.XML.parse(XML.java:380)
    at org.json.XML.parse(XML.java:380)
    at org.json.XML.parse(XML.java:380)
    at org.json.XML.toJSONObject(XML.java:458)
    at money.paybox.payboxsdk.Utils.ParseUtils.xmlToJson(ParseUtils.java:87)
    at money.paybox.payboxsdk.Utils.PBResultReceiver.onReceiveResult(PBResultReceiver.java:62)
    at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6682)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

P.S. sdk already initialized
P.P.S. initNewPayment method successfully works

**Comment by PayBoxKAZ** [comment]
This method must be approved before using
